#pragma once

#include "CoreMinimal.h"
#include "WingBasics.h"
#include "WingServer.h"
#include "WingManual.h"
#include "Documentation_CreateAssets.generated.h"

UCLASS()
class UWing_Documentation_CreateAssets : public UWingHandler
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, meta=(Description="Substring filter for command names"))
	FString Query;

	UPROPERTY(EditAnywhere, meta=(Description="If true, return full details including parameter types and descriptions"))
	bool Verbose = false;

	virtual void Register() override
	{
		UWingServer::AddHandler(this,
			TEXT("List all the create commands that create new assets."));
	}
	virtual void Handle() override
	{
		WingManual::Commands(EWingHandlerKind::Create, Query, Verbose);
	}
};
